/* Built-in exercise library, grouped by primary muscle. */
const MUSCLE_GROUPS = [
  "Chest",
  "Back",
  "Shoulders",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Biceps",
  "Triceps",
  "Calves",
  "Core",
];

const EXERCISES = [
  // Chest
  { id: "bench-press", name: "Barbell Bench Press", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg" },
  { id: "incline-bench", name: "Incline Bench Press", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg" },
  { id: "db-bench", name: "Dumbbell Bench Press", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg" },
  { id: "incline-db", name: "Incline Dumbbell Press", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg" },
  { id: "chest-fly", name: "Dumbbell Chest Fly", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg" },
  { id: "cable-fly", name: "Cable Fly", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg" },
  { id: "pec-deck", name: "Pec Deck Machine", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg" },
  { id: "pushup", name: "Push-Up", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg" },
  { id: "dip-chest", name: "Chest Dip", muscle: "Chest", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Chest_Version/0.jpg" },
  // Back
  { id: "deadlift", name: "Barbell Deadlift", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg" },
  { id: "pullup", name: "Pull-Up", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg" },
  { id: "chinup", name: "Chin-Up", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg" },
  { id: "lat-pulldown", name: "Lat Pulldown", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg" },
  { id: "bb-row", name: "Barbell Row", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg" },
  { id: "db-row", name: "Dumbbell Row", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg" },
  { id: "seated-row", name: "Seated Cable Row", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg" },
  { id: "tbar-row", name: "T-Bar Row", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row_with_Handle/0.jpg" },
  { id: "face-pull", name: "Face Pull", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg" },
  { id: "back-ext", name: "Back Extension", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg" },
  { id: "shrug", name: "Barbell Shrug", muscle: "Back", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg" },
  // Shoulders
  { id: "ohp", name: "Overhead Press", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg" },
  { id: "db-shoulder", name: "Dumbbell Shoulder Press", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg" },
  { id: "arnold", name: "Arnold Press", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg" },
  { id: "lateral-raise", name: "Lateral Raise", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg" },
  { id: "front-raise", name: "Front Raise", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg" },
  { id: "rear-delt-fly", name: "Rear Delt Fly", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Flyes/0.jpg" },
  { id: "upright-row", name: "Upright Row", muscle: "Shoulders", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg" },
  // Quads
  { id: "squat", name: "Barbell Back Squat", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg" },
  { id: "front-squat", name: "Front Squat", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg" },
  { id: "leg-press", name: "Leg Press", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg" },
  { id: "leg-ext", name: "Leg Extension", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg" },
  { id: "lunge", name: "Walking Lunge", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Walking_Lunge/0.jpg" },
  { id: "bulgarian", name: "Bulgarian Split Squat", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Rear_Lunge/0.jpg" },
  { id: "hack-squat", name: "Hack Squat", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg" },
  { id: "goblet-squat", name: "Goblet Squat", muscle: "Quads", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg" },
  // Hamstrings
  { id: "rdl", name: "Romanian Deadlift", muscle: "Hamstrings", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg" },
  { id: "leg-curl", name: "Lying Leg Curl", muscle: "Hamstrings", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg" },
  { id: "seated-curl", name: "Seated Leg Curl", muscle: "Hamstrings", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg" },
  { id: "good-morning", name: "Good Morning", muscle: "Hamstrings", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg" },
  { id: "nordic-curl", name: "Nordic Curl", muscle: "Hamstrings", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lower_Back_Curl/0.jpg" },
  // Glutes
  { id: "hip-thrust", name: "Barbell Hip Thrust", muscle: "Glutes", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg" },
  { id: "glute-bridge", name: "Glute Bridge", muscle: "Glutes", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butt_Lift_Bridge/0.jpg" },
  { id: "cable-kickback", name: "Cable Glute Kickback", muscle: "Glutes", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickback/0.jpg" },
  { id: "sumo-deadlift", name: "Sumo Deadlift", muscle: "Glutes", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg" },
  // Biceps
  { id: "bb-curl", name: "Barbell Curl", muscle: "Biceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg" },
  { id: "db-curl", name: "Dumbbell Curl", muscle: "Biceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg" },
  { id: "hammer-curl", name: "Hammer Curl", muscle: "Biceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg" },
  { id: "preacher-curl", name: "Preacher Curl", muscle: "Biceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg" },
  { id: "concentration-curl", name: "Concentration Curl", muscle: "Biceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg" },
  { id: "cable-curl", name: "Cable Curl", muscle: "Biceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hammer_Curls_-_Rope_Attachment/0.jpg" },
  // Triceps
  { id: "tricep-pushdown", name: "Tricep Pushdown", muscle: "Triceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg" },
  { id: "skullcrusher", name: "Skullcrusher", muscle: "Triceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Press/0.jpg" },
  { id: "overhead-ext", name: "Overhead Tricep Extension", muscle: "Triceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg" },
  { id: "dip-tricep", name: "Tricep Dip", muscle: "Triceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/0.jpg" },
  { id: "close-grip-bench", name: "Close-Grip Bench Press", muscle: "Triceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg" },
  { id: "kickback", name: "Tricep Kickback", muscle: "Triceps", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/0.jpg" },
  // Calves
  { id: "standing-calf", name: "Standing Calf Raise", muscle: "Calves", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg" },
  { id: "seated-calf", name: "Seated Calf Raise", muscle: "Calves", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg" },
  { id: "calf-press", name: "Calf Press on Leg Press", muscle: "Calves", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/0.jpg" },
  // Core
  { id: "plank", name: "Plank", muscle: "Core", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg" },
  { id: "crunch", name: "Crunch", muscle: "Core", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/0.jpg" },
  { id: "hanging-raise", name: "Hanging Leg Raise", muscle: "Core", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg" },
  { id: "russian-twist", name: "Russian Twist", muscle: "Core", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg" },
  { id: "cable-crunch", name: "Cable Crunch", muscle: "Core", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg" },
  { id: "ab-wheel", name: "Ab Wheel Rollout", muscle: "Core", img: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg" },
];
